config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    post 'downgrade_user' => 'users#downgrade_user', as: :downgrade_user
  end
     
  
    
  resources :wikis
  resources :charges, only: [:new, :create]
  
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaborators
  has_many :wikis, :through => :collaborators
  
  enum role: [:admin, :member, :premium]
  after_initialize :set_default_role
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  def admin?
    role == "admin"
  end
  
  def member?
    role == "member"
  end
  
  def premium?
    role == "premium"
  end
  
  def set_default_role
    self.role ||= :member
  end
  
  def upgrade
    self.role = 'premium'
    self.save
  end
  
  def downgrade
    self.role = 'member'
    make_wikis_public
    self.save
  end
  
  def make_wikis_public
    self.wikis.each do |w| 
      w.update(private: false)
    end
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, :through => :collaborators
  
  default_scope { order('updated_at desc') }
  
  scope :free, -> { where(private: false) }
  scope :not_private, -> (user) { user.premium? ? all : free }
  
end

app/controllers/amount.rb
module Amount
  attr_accessor :charge
  
  def default
    charge = 1500
    charge
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include Pundit
end

app/controllers/charges_controller.rb
include Amount
include ChargesHelper

class ChargesController < ApplicationController
  def create
   
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
      )
      
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Blocipedia Premium Membershp - #{current_user.email}",
      currency: 'usd'
      )
      
    flash[:notice] = "Thanks for joining Blocipedia, #{current_user.email}!"
    
    current_user.upgrade
    redirect_to root_path(current_user)
    
    rescue Stripe::CardError => e
      current_user.downgrade_user
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
  
  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Blocipedia premium membership - #{current_user.email}",
     amount: Amount.default
   }
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def downgrade_user
    current_user.downgrade
    redirect_to root_path
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  
  def index
    @wikis = policy_scope(Wiki)
  end
  
  def show
    @wiki = Wiki.find(params[:id])
  end
  
  def new
    @user = current_user.id
    @wiki = Wiki.new
    authorize @wiki
  end
  
  def create
    @wiki = Wiki.new(wiki_params)
    authorize @wiki
    @wiki.user = current_user
    
    if @wiki.save
      redirect_to @wiki, notice: "Wiki created successfully"
    else
      flash[:error] = "Error creating Wiki"
      render :new
    end
  end
  
  def edit
    @users = User.all
    @wiki = Wiki.find(params[:id])
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    
    if @wiki.save
      redirect_to @wiki, notice: "Wiki Updated"
    else
      flash[:error] = "Error updating wiki"
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the Wiki."
      render :show
    end
  end

  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, user_ids: [])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_text(text)
    renderer = Redcarpet::Render::HTML.new(filter_html: true, no_styles: true, prettify: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true, )
    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia Wikis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container" >
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <% if current_user.role == 'premium' %>
            <strong>Premium</strong>
            
          <% else %>
            <strong>FREE</strong> |
            <%= link_to "Upgrade to Premium", new_charge_path, :class => 'navbar-link' %>
          <% end %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>Blocipedia</h1>
<p>Created by Lucas Konopka</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <div class="container">
    <div class="col-lg-10 col-md-offset-2 centerfy">
      <h1>Welcome to Blocipedia</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4" >
      <div class="well well-sm">
        <h3>Create and Share Markdown Wikis</h3>
        <% if current_user %>
          <%= link_to "Create a Wiki", new_wiki_path, class: 'btn btn-primary' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3 col-md-offset-2">
    <h3>Create as many public Wikis as you want</h3>
  </div>
  
  <div class="col-md-3 col-md-offset-2">
    <h3>Create private Wikis</h3>
  </div>
  
  
   
  <div class="col-md-3">
    <% if current_user && current_user.role == 'premium' %>
      <p>Need to Downgrade your account?</p>
      <%= button_to "Downgrade", user_downgrade_user_path(current_user), method: :post %>
    <% end %>
  </div>
  
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<%= form_for @wiki do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    
    <div class="field">
    <p>Collaborators</p>
    <% @users.each do |user| %>
      <%= check_box_tag "wiki[user_ids][]", user.id, @wiki.user_ids.include?(user.id) %>
      <%= user.email %><br>
    <% end %>
    </div>
  
   
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
    
<% end %>

app/views/wikis/index.html.erb
<br>

<div class="row">
  <h2>Wikis</h2>
  <% @wikis.each do |w| %>
    <h3><%= link_to w.title, w %> </h3>
  <% end %>
</div>

app/views/wikis/new.html.erb
<%= form_for @wiki do |f| %>
  
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    
    <% if current_user.role == 'premium' || current_user == 'admin' %>
        <div class = "form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private Wiki 
          <% end %>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    
    
  
<% end %>
  

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<p><%= markdown_text(@wiki.body) %></p>

<h3>Collaborators</h3>
<ul>
  <% @wiki.collaborators.each do |c| %>
    <li><%= User.find(c.user_id).email %></li>
  <% end %>
</ul>